'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DnD5eCharacterTracker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJvSURBVDjLpZPrS5NhGIf9W7YvBYOkhlkoqCklWChv2WyKik7blnNris72bi6dus0DLZ0TDxW1odtopDs4D8MDZuLU0kXq61CijSIIasOvv94VTUfLiB74fXngup7nvrnvJABJ/5PfLnTTdcwOj4RsdYmo5glBWP6iOtzwvIKSWstI0Wgx80SBblpKtE9KQs/We7EaWoT/8wbWP61gMmCH0lMDvokT4j25TiQU/ITFkek9Ow6+7WH2gwsmahCPdwyw75uw9HEO2gUZSkfyI9zBPCJOoJ2SMmg46N61YO/rNoa39Xi41oFuXysMfh36/Fp0b7bAfWAH6RGi0HglWNCbzYgJaFjRv6zGuy+b9It96N3SQvNKiV9HvSaDfFEIxXItnPs23BzJ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJdSURBVDjLpZP7S1NhGMf9W7YfogSJboSEUVCY8zJ31trcps6zTI9bLGJpjp1hmkGNxVz4Q6ildtXKXzJNbJRaRmrXoeWx8tJOTWptnrNryre5YCYuI3rh+8vL+/m8PA/PkwIg5X+y5mJWrxfOUBXm91QZM6UluUmthntHqplxUml2lciF6wrmdHriI0Wx3xw2hAediLwZRWRkCPzdDswaSvGqkGCfq8VEUsEyPF1O8Qu3O7A09RbRvjuIttsRbT6HHzebsDjcB4/JgFFlNv9MnkmsEszodIIY7Oaut2OJcSF68Qx8dgv8tmqEL1gQaaARtp5A+N4NzB0lMXxon/uxbI8gIYjB9HytGYuusfiPIQcN71kjgnW6VeFOkgh3XcHLvAwMSDPo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAPruSURBVHhe7F0FgB1F0q5nK8nGhSRAgpMQ3N3d3V0OODjk4LDD3Y+7Aw4IDoe7y+EWJARIiGNx4rv73Oqvr2r6zezb9zYBAmTzU0nvzOuZqa7urqquag2xAJUBYjRS/oRCGtUKqsX/AX/AH/DbQ2spNkC8k9VKMttKARSLROGw96MNwHvBL8uRV0zsD6XxB/wB84VKwlweVy57Cyqz5e+VFAD+OgGdN69ATc1heSgfRIiiUZbgXWNMMbmvqZE/PxEKhepKAPF/KIg/4P8DQNbKBdoB4iMicz8Vstk85XJE+XzIC3ZfFJkjkatOnYrUtashDsq6KgA/okh33ZWkIXdEaPyEGtEYIaqtY+rSuUANDUVF0knuu3ZmGjiwlurqhVjRKLV1RB0bCtSx [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Logo_256() As String
            Get
                Return ResourceManager.GetString("Logo-256", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUIAAAFCCAYAAACErdScAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAACcHSURBVHhe7d15c1vXmSbwlyQAkgAB7jspapft1Nhy7HTGcbwlTnriaLoq6TiZ1FR1UtXJfKhJ0n/0dDpxMuWkJtOJnLS3kWXHi7x0YmuxJErivgEkSGIlqTnPuRcUREMSCPLiHuA8PxcMAQSxEffBe5Z7bsNSYuWmEBFZrNE9JyKyFoOQiKzHICQi6zEIich6DEIish6DkIisxyAkIusxCInIegxCIrIeg5CIrMcgJCLrMQiJyHoMQiKyHoOQiKzHICQi6zEIich6DEIish6DkIisxyAkIusxCInIegxCIrIeg5CIrMcgJCLrMQiJyHoMQiKyHoOQiKzHICQi6zEIich6DEIish6DkIisxyAkIusxCInIegxCIrIeg5CIrMcgJCLrMQiJyHoM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SuchEmpty() As String
            Get
                Return ResourceManager.GetString("SuchEmpty", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
